#      NOTE: I RECOMMEND COMPLETELY RESETTING ALL DEATH COUNTS ANYTIME YOU MAKE A CHANGE
#            TO THIS CONFIGURATION FILE, I HAVE FULLY TESTED ALL OPTIONS FROM A FRESH START
#            BUT CANT PROMISE CHANGING SOMETHING WON'T BREAK PROGRAM LOGIC IF PEOPLE ALREADY HAVE
#            DEATH COUNTS FROM A DIFFERENT CONFIGURATION SETUP


# This variable chooses if you want incrementation
# or a multiplier for your auto bans, false for multiplier, true for increment.
#
# increment ex: 1st death banned 1 hour, 2nd death banned 2 hours, 3rd death banned 3 hours etc.
# multiplier ex: 1st death banned 1 hour, 2nd death banned 2 hours, 3rd death banned 4 hours etc.
incOrMultiply: false

# This is the length of your initial ban in milliseconds if incOrMultiply is set to true (increment)
# its also how many milliseconds will be added each ban.
#
# ex: 3600000 milliseconds = 1 hour, first death will be 1 hour ban, second death will add 3600000
#     (7200000) for a 2-hour ban
incrementByXMilliseconds: 3600000

# This is the length of your initial ban in milliseconds if incOrMultiply is set to false (multiply).
initialBanLength: 3600000

# This is how much the baseMulti will be multiplied by for each death.
#
# ex: 1st death (3600000 milliseconds/1 hour ban)
# ex: 2nd death (3600000 * 2 = 7200000 milliseconds/2 hour ban)
# ex: 3rd death (7200000 * 2 = 14400000 milliseconds/4 hour ban)
multiplier: 2


# This is the message that will be broadcasted when a player dies
#
# messageContainer is the message that will be displayed to the server when someone dies and is banned
# banLengthContainer is a message that will display under message container, in order to show the ban length
# graceMessageContainer is the message that will be displayed when the user has grace lives remaining after dying (if grace is set to 0 in this config it will never display)
#
# type [player] to use the players name in the message
# type [dc] to use the players death count in the message like (1,2 or 3)
# type [dcth] to use players death count like (1st, 2nd, or 3rd)
# type [bl] to use the amount of time they've been banned in words
# type [gr] to use the amount of graces remaining for a player before they're banned (only use in graceMessageContainer)
# minecraft color codes are supported, for color keys look here https://htmlcolorcodes.com/minecraft-color-codes/
messageContainer: "§e[§lTempDeathBanner§l] §c[player]§a has died for the §c[dcth]§a time, they have been banned for their failure"
graceMessageContainer: "§e[§lTempDeathBanner§l] §c[player]§a has died for the §c[dcth]§a time, they have §c[gr]§a deaths remaining before they'll be banned"
banLengthContainer: "§e[§lBan Length]§l §c[bl]"


# This number represents the amount of times a player can die before they start to receive
# penalties for their deaths, set to 0 for no grace lives
#
# grace: 2
# ex: death 1: "thats a freebie, no ban"
# ex: death 2: "thats a freebie, no ban"
# ex: death 3: "player has died for the third time, ban length: 1 hour"
graceLives: 0


# This is an option to set a maximum ban length, this will be the maximum amount of milliseconds
# somebody can be banned, set to -1 for no maximum length
# maxBanLength = 7200000 (2 hours)
# death 1: "player died for first time, ban length 1 hours"
# death 2: "player died for the second time, ban length 2 hours"
# death 3: "player died for the third time, ban length 2 hours" (maximum ban length was hit so they will never go higher)
maximumBanLength: -1


# This is how to set the scoreBoardTitle
scoreboardTitle: '§e§l[TDB] Death Leaders'

