name: TempDeathBanner
authors: [ flyingtaco725 ]
description: simple hello world plugin
version: '1'
main: me.flyingtaco725.tempDeathBanner.TempDeathBanner
api-version: '1.20'

commands:
  tdb:
    description: Temp Death Banner commands
    usage: /<command> [resetdeaths|resetdeathsall|showdeathboard|closedeathboard]
    aliases: [tempdeathbanner]
    permission: tempdeathbanner.use
    children:
      resetdeaths:
        description: Reset death count for a specific player
        usage: /<command> resetdeaths <playerName>
        permission: tempdeathbanner.resetdeaths
      resetdeathsall:
        description: Reset death count for all players
        usage: /<command> resetdeathsall
        permission: tempdeathbanner.resetdeathsall
      showdeathboard:
        description: Show whos died the most
        usage: /<command> showdeathboard
        permission: tempdeathbanner.showdeathboard
      closedeathboard:
        description: close the death board
        usage: /<command> closedeathboard
        permission: tempdeathbanner.closedeathboard

permissions:
  tempdeathbanner.use:
    description: Allows usage of Temp Death Banner commands
    default: true
  tempdeathbanner.resetdeaths:
    description: Allows resetting death count for a specific player
    default: op
  tempdeathbanner.resetdeathsall:
    description: Allows resetting death count for all players
    default: op
  tempdeathbanner.showdeathboard:
    description: Allows showing death score board
    default: op
  tempdeathbanner.closedeathboard:
    description: Allows closing death score board
    default: op